; This file is for the FamiStudio Sound Engine and was generated by FamiStudio

.if FAMISTUDIO_CFG_C_BINDINGS
.export _music_main_game=music_main_game
.endif

music_main_game:
	.byte 1
	.word @instruments
	.word @samples-4
; 00 : Evil Clockwork
	.word @song0ch0
	.word @song0ch1
	.word @song0ch2
	.word @song0ch3
	.word @song0ch4
	.byte .lobyte(@tempo_env_1_mid), .hibyte(@tempo_env_1_mid), 0, 0

.export music_main_game
.global FAMISTUDIO_DPCM_PTR

@instruments:
	.word @env5,@env9,@env6,@env0 ; 00 : OH(F#3)
	.word @env12,@env4,@env6,@env0 ; 01 : snare attack(D3)
	.word @env13,@env10,@env6,@env0 ; 02 : kick attack(E3)
	.word @env11,@env1,@env6,@env0 ; 03 : crash(F#3)
	.word @env2,@env4,@env8,@env0 ; 04 : Lead 25 25 12.5
	.word @env2,@env4,@env14,@env0 ; 05 : Lead 50 50 25
	.word @env3,@env15,@env6,@env0 ; 06 : Tribass sub

@env0:
	.byte $00,$c0,$7f,$00,$02
@env1:
	.byte $c0,$c0,$c2,$00,$02
@env2:
	.byte $06,$cd,$ca,$c9,$00,$03,$c1,$00,$06
@env3:
	.byte $00,$cf,$7f,$00,$02
@env4:
	.byte $c0,$7f,$00,$01
@env5:
	.byte $00,$c9,$03,$c7,$c0,$00,$04
@env6:
	.byte $7f,$00,$00
@env7:
	.byte $00,$c0,$bc,$ba,$bc,$c0,$c4,$c6,$c4,$00,$01
@env8:
	.byte $c1,$c1,$c0,$00,$02
@env9:
	.byte $c0,$c2,$00,$01
@env10:
	.byte $c0,$c4,$00,$01
@env11:
	.byte $00,$ca,$02,$c9,$03,$c8,$03,$c7,$03,$c6,$03,$c5,$03,$c4,$03,$c3,$03,$c2,$03,$c1,$00,$13
@env12:
	.byte $00,$cd,$c7,$c6,$c5,$c5,$c4,$03,$c3,$00,$08
@env13:
	.byte $00,$c5,$c3,$c2,$c1,$c0,$00,$05
@env14:
	.byte $c2,$c2,$c1,$00,$02
@env15:
	.byte $cc,$c0,$00,$01

@samples:

@tempo_env_1_mid:
	.byte $03,$05,$80

@song0ch0:
@song0ch0loop:
	.byte $47, .lobyte(@tempo_env_1_mid), .hibyte(@tempo_env_1_mid)
@song0ref5:
	.byte $ff, $9f, $48, $ff, $9f, $48, $ff, $9f, $48, $ff, $9f, $48
	.byte $41, $08
	.word @song0ref5
	.byte $42
	.word @song0ch0loop
@song0ch1:
@song0ch1loop:
	.byte $7f, $88, $27, $85, $43, $29, $87, $45, $76, $29, $85, $45, $7f, $28, $85, $45, $25, $8f, $45, $76, $25, $85, $45, $7f
	.byte $22, $85, $45, $27, $8f, $45, $76, $27, $85, $45, $7f, $25, $85, $45, $22, $8f, $45, $76, $22, $85, $45, $7f, $20, $85
	.byte $45, $1d, $8f, $45, $76, $1d, $85, $45, $20, $85, $45, $7f, $25, $91, $43, $50, $24, $31, $2b, $87, $43, $1f, $85, $45
	.byte $00, $91, $24, $85, $43, $25, $49, .lobyte(@env7), .hibyte(@env7), $93, $43, $50, $56, $31, $25, $87, $49, .lobyte(@env0)
	.byte .hibyte(@env0), $4a, $88, $25, $85, $45, $24, $85, $45, $22, $8f, $45, $25, $8f, $45, $22, $8f, $45, $20, $85, $45
	.byte $00, $87, $1c, $85, $43, $1d, $87, $45, $20, $85, $45, $00, $87, $1d, $8f, $45, $19, $85, $45, $00, $87, $1c, $8f, $45
	.byte $1b, $85, $45, $00, $87, $19, $8f, $45, $15, $85, $43, $16, $49, .lobyte(@env7), .hibyte(@env7), $9f, $43, $50, $72
	.byte $22, $16, $8f, $49, .lobyte(@env0), .hibyte(@env0), $4a, $00, $a5, $88, $16, $87, $43, $19
@song0ref192:
	.byte $85, $45, $1d, $85, $45, $20, $87, $43, $22
	.byte $41, $08
	.word @song0ref192
	.byte $87, $43, $25, $85, $45, $29, $85, $45, $2c, $87, $43, $2e, $85, $45, $31, $87, $43, $35, $87, $43, $31, $85, $45, $2e
	.byte $85, $45, $34, $87, $43, $33, $85, $45, $31, $85, $45, $2e, $85, $45, $31, $87, $43, $2e, $85, $45, $2c, $85, $45, $29
	.byte $85, $45, $2c, $87, $43, $29, $85, $45, $25, $85, $45, $29, $87, $43, $25, $85, $45, $22, $85, $45, $20, $87, $43, $22
	.byte $85, $45, $8a
@song0ref279:
	.byte $2a, $87, $43, $22, $87, $43, $25, $87, $2a, $87, $43, $22, $87, $43, $25, $87
	.byte $41, $0c
	.word @song0ref279
	.byte $2a, $87, $43, $22, $87, $43, $25, $87, $43, $2a, $87, $2c, $87, $43, $27, $87, $2c, $87, $43, $27, $87, $2c, $87, $43
	.byte $27, $87, $30, $87, $43, $2c, $87, $30, $87, $43, $2c, $87, $30, $87, $43, $2c, $87, $43, $50, $fe, $36, $38, $a5, $42
	.word @song0ch1loop
@song0ch2:
@song0ch2loop:
	.byte $8c
@song0ref350:
	.byte $08, $87, $43, $0a, $97
@song0ref355:
	.byte $00, $81, $16, $87, $43, $50, $7f, $22, $16, $87, $0a, $83, $00, $81, $0a, $83, $00, $81, $14, $8d, $00, $81, $11, $8d
	.byte $00, $81, $14, $8d, $00, $81, $0a, $8d, $00, $81, $11, $8d, $00, $81, $0a, $8d, $00, $81, $10, $8d, $00, $81, $0a, $8d
	.byte $00, $81, $0f, $8d, $00, $81, $0d, $8d, $00, $81, $08, $8d, $00, $81, $08, $87, $43, $0a, $87, $a3
	.byte $41, $1a
	.word @song0ref355
	.byte $16, $8d, $00, $81, $12, $8d, $00, $81, $06, $8d, $00, $81, $12, $8d, $00, $81, $11, $a1, $00, $81, $11, $83, $00, $81
	.byte $11, $83, $00, $81, $14, $8d, $00, $81, $15, $8d, $00, $81
	.byte $41, $37
	.word @song0ref350
	.byte $97, $00, $81, $0c, $83, $00, $81, $0d, $83, $00, $81, $0e, $83
@song0ref478:
	.byte $00, $81, $03, $8d, $00, $81, $0f, $8d
	.byte $41, $08
	.word @song0ref478
	.byte $41, $08
	.word @song0ref478
	.byte $00, $81, $0d, $8d, $00, $81, $0f, $8d, $00, $81, $05, $8b, $00, $83, $05, $8b, $00, $83, $05, $8b, $00, $83, $05, $95
	.byte $00, $83, $05, $81, $00, $83, $05, $8b, $00, $83, $08, $8b, $00, $83, $09, $8b, $00, $83, $42
	.word @song0ch2loop
@song0ch3:
@song0ch3loop:
	.byte $7f
@song0ref539:
	.byte $86, $1f, $a5
@song0ref542:
	.byte $82, $1c, $91, $80, $1f, $91, $84, $1d, $87, $00, $87, $80, $1f, $91
	.byte $41, $0a
	.word @song0ref542
	.byte $41, $0a
	.word @song0ref542
	.byte $41, $0a
	.word @song0ref542
	.byte $41, $0a
	.word @song0ref542
	.byte $41, $0a
	.word @song0ref542
	.byte $41, $0a
	.word @song0ref542
	.byte $82, $1c, $91, $1c, $91
	.byte $41, $0c
	.word @song0ref539
	.byte $41, $0a
	.word @song0ref542
	.byte $82, $1c, $91, $80, $1f, $91, $00, $91, $1f, $91
	.byte $41, $0a
	.word @song0ref542
	.byte $41, $0a
	.word @song0ref542
	.byte $82, $1c, $91, $80
@song0ref605:
	.byte $1f, $91, $82, $1c, $91, $84, $1d, $87, $00, $87, $86
	.byte $41, $08
	.word @song0ref605
	.byte $86, $1f, $91, $82, $1c, $91, $1c, $91, $42
	.word @song0ch3loop
@song0ch4:
@song0ch4loop:
@song0ref631:
	.byte $ff, $9f, $ff, $9f, $ff, $9f, $ff, $9f
	.byte $41, $08
	.word @song0ref631
	.byte $42
	.word @song0ch4loop
